### ISSUE TITLE
Restore Cursor When WinLeave Occurs

### ISSUE THREAD

**Issue by jalcine** [jszakmeister/vim-togglecursor#16]
I noticed that whilst in Insert mode and switching to another pane in tmux that my cursor didn't preserve its normal block state. I'm opening this issue to gauge interest in a patch that'd fix this.

**Comment by jszakmeister** [comment]
I guess changing panes in tmux doesn't restore the cursor, and I guess I understand why: you can't really interrogate the terminal for the current shape.  I could see that being useful, though I'm not sure if WinLeave is going to do it for you or not.  And I wouldn't want it to change when not under tmux either.  What would you do when the pane regained focus?  Presumably, you're still in insert mode and would want the cursor to switch back?

**Comment by jalcine** [comment]
Interesting point. I'd ideally would like the cursor to be restored to the original state it was in when it was visible in Vim.

**Comment by jalcine** [comment]
But to that point, I guess it might be moot. I was debating working on a patch later tonight or tomorrow to not only experiment if this'd work or not. Vim's a bit vague on what makes [`:WinLeave`](http://vimhelp.appspot.com/autocmd.txt.html#WinLeave) get triggered as well, so I'll toy around. Thanks for considering it!

**Comment by wadkar** [comment]
I bumped into this issue myself, not a deal breaker but I understand how this is a complicated issue. @jszakmeister were you able to find anything interesting on this? If not thats fine, we can leave this issue as closed. Perhaps mention this in docs/README as known _issue_?

**Comment by jszakmeister** [comment]
I did not--though tmux might cope better these days.  I don't really use tmux that way, so I don't run into this issue.  You could try disabling the tmux pass-thru and see.
