### ISSUE TITLE
urxvt should be supported

### ISSUE THREAD

**Issue by andrea-chiavazza** [jszakmeister/vim-togglecursor#21]
The latest version of urxvt (9.21 - 31/12/2014) added the DECSCUSR xterm extension to set the cursor to a vertical bar.
See http://dist.schmorp.de/rxvt-unicode/Changes
So it would be nice if urxvt could be whitelisted somehow.

**Comment by jszakmeister** [comment]
I don't use urxvt... is there some way of detecting that you're running under it?

**Comment by jszakmeister** [comment]
BTW, if you use rxvt all the time (and don't have to worry about running other terminals), then you could use:

```vim
let g:togglecursor_force = 'xterm'
```

in your .vimrc to force using the DECSCUSR sequence, as described in the [documentation](https://github.com/jszakmeister/vim-togglecursor/blob/master/doc/togglecursor.txt#L57).

**Comment by andrea-chiavazza** [comment]
Yes, adding `let g:togglecursor_force = 'xterm'` works.

With urxvt `:set term` returns `term=rxvt-unicode-256color`
So a conditional like this one can be used to check for urxvt:
`if &term =~ "rxvt-unicode"`
Or to check for xterm or urxvt:
`if &term =~ "xterm\\|rxvt-unicode"`

I'm not sure whether rxvt supports DECSCUSR. I think it doesn't, otherwise you could just test for the "rxvt" string.

**Comment by jszakmeister** [comment]
> `if &term =~ "rxvt-unicode"`

That's not really enough of a solution for me to put it into vim-togglecursor.  If the plugin attempts to send the sequence to a terminal that doesn't support it, it will corrupt their screen.  There needs to be something more concrete that the plugin can key off of to know that the version running supports DECSCUSR properly.  I much rather be conservative (do no harm) than to make it behave badly out-of-the-box for people.

**Comment by andrea-chiavazza** [comment]
I suppose you could try and parse the first line of the output of running "urxvt -h" in order to check that the version is at least 9.21, but I'm not really sure how to do it from vim, and it would be a bit of a hack.
I guess it just depends on what your priorities are for this plugin: try to work in all cases, or keep it clean and avoid hackery code.

**Comment by jszakmeister** [comment]
> I suppose you could try and parse the first line of the output of running "urxvt -h" in order to check that the version is at least 9.21

Unfortunately, that's not a solution either.  Just because term is set to `rxvt-unicode` doesn't mean that the terminal emulator is urxvt--it could be a different terminal emulator with the encoding set to `rxvt-unicode`.

Unless urxvt is setting a shell variable that's unique to it, then it's probably not possible to do this in a suitable manner.  Sorry!
