### ISSUE TITLE
Not work when run vim as root

### ISSUE THREAD

**Issue by phphong** [jszakmeister/vim-togglecursor#24]
When I run `sudo vim`, the plugin does not work (cursor does not change shape). How can I overcome this problem?

**Comment by jszakmeister** [comment]
The sudo program cleanses the environment, and togglecursor works by attempting to deduce the terminal emulator that you are running under by examining the environment.  If you haven't setup /etc/sudoers to forward this environmental information, then togglecursor cannot detect the emulator, and will not enable itself.

What to forward depends on the terminal you're using.  Something like this in /etc/sudoers should handle your case with gnome-terminal:

```text
Defaults env_keep += "VTE_VERSION"
```

The alternative would be to set `g:togglecursor_force` to something you know will work, which will bypass the auto-detection.

**Comment by jszakmeister** [comment]
I added some notes about sudo [here](https://github.com/jszakmeister/vim-togglecursor/blob/867fa90c48afc17144f744e3c90775f99bbfd559/doc/togglecursor.txt#L183).
