### ISSUE TITLE
It doesn't work on ubuntu gnome-termianl-3.14-2?

### ISSUE THREAD

**Issue by lyerox** [jszakmeister/vim-togglecursor#25]
I have installed this plugin via vundle, but it seems doesn't work at all.
my terminal-version is gnome-terminal-3.14.2

**Comment by jszakmeister** [comment]
What does `echo $VTE_VERSION` show you at the command line?  If it's less than 3900 or is nothing, then it's not new enough to support the DECSCUSR sequences necessary to alter the cursor.

**Comment by lyerox** [comment]
yeah , the VTE_VERSION is 3803 , how can I get appropriate  vte version?

**Comment by lyerox** [comment]
yeah, the origin version is 3803,  I have upgraded to 4002. 
Now , It works well . thanks

**Comment by jszakmeister** [comment]
Great!
