### ISSUE TITLE
nvim issue when using xfce4-terminal

### ISSUE THREAD

**Issue by kurkale6ka** [jszakmeister/vim-togglecursor#30]
`xfce4-terminal` doesn't support `DECSCUSR`.
Even so, the plugin seems to think it does.
Entering insert mode in nvim I get this: `-- INSERT --[5 q`

**Comment by jszakmeister** [comment]
Hmmm... for Neovim support, it just detects the fact that you're running under Neovim and turns on `NVIM_TUI_ENABLE_CURSOR_SHAPE` under the assumption that you have this plugin, so you must want that support.

Perhaps I can do a little better and detect the terminal like we do under Vim and only-enable for xterm style terminals.  The down side is that I expect Neovim to eventually query the terminal itself, and that would make its detection far superior.  That is why I did not take that approach and am loathe to take it now.

For now, you can disable the Neovim support with:

    let g:togglecursor_disable_neovim = 1

**Comment by kurkale6ka** [comment]
Yes, I think it's better to use this workaround and wait for nvim's next tui upgrade.
Thanks
