### ISSUE TITLE
Fontsize reset upon cursor/mode change, on Konsole 16.08.0

### ISSUE THREAD

**Issue by emugel** [jszakmeister/vim-togglecursor#32]
First of all thanks for this great plugin. 
On urxvt I don't encounter this problem, however on Konsole, whenever I change the font size (using Ctrl- Or Ctrl+), the font size is reset whenever the cursor changes. 
My config is simple:

```
let g:togglecursor_default = "block"
let g:togglecursor_insert  = "line"
let g:togglecursor_leave   = "block"
let g:togglecursor_replace = "underline"
```

Any idea? Thanks again!

**Comment by jszakmeister** [comment]
Sorry I didn't see this... I don't seem to have ever gotten notification of your issue--and unfortunately, this is not the first time. :-(

Unfortunately, no.  I suspect it's probably a bug with Konsole and it's re-applying the configuration when changing font size.  It's probably best to file an issue with them.

**Comment by lookforit** [comment]
@emugel @jszakmeister 
I met with the same issue.
When I turned the font size smaller,and switched from normal mode to insert mode ,the font size resized automatically.
Under the konsole 16.12.3

**Comment by jszakmeister** [comment]
Again, this is an issue with Konsole, not my plugin.  It'd be best to file a ticket with the KDE/Konsole guys.
