### ISSUE TITLE
Doc update - works in MacOS Sierra Terminal now

### ISSUE THREAD

**Issue by jcartledge** [jszakmeister/vim-togglecursor#33]
Hi,

Just noting that since upgrading to MacOS 10.12 Sierra vim-togglecursor now works fine in version 2.7 of the default mac Terminal application, at least in neovim. I haven't tested in vanilla vim.

![image](https://cloud.githubusercontent.com/assets/33946/18819883/7afb1d7a-83db-11e6-9a25-16285f1fb69b.png)

Thanks!

**Comment by jszakmeister** [comment]
Yay!  Thanks!

**Comment by jszakmeister** [comment]
Ah, Neovim actually does it's own thing.  I'll check and see what style it's using... because my plugin supports it all.
