### ISSUE TITLE
Not working inside Vagrant

### ISSUE THREAD

**Issue by PezCoder** [jszakmeister/vim-togglecursor#34]
### What ?
My VIM is inside a vagrant (virtual box) with linux OS having VIM 8.0.134
The cursor is not changing when I change the modes in it.

### Possible Issues
I think since this plugin depends on what type of terminal it is, it mightn't be able to detect it.

### Other observations
- Outside the box I have VIM 7.3 & this plugin works perfectly in it.
- Inside the virtual box I have neovim with which this works as expected.

**Comment by jszakmeister** [comment]
This is not a vim-togglecursor problem--you need to get some environment variables over to the remote system, and that's an SSH issue.

As for why it works with Neovim, I can't answer that.  AFAIK, it looks for environment variables too.  Neovim at least has the option to talk to the terminal, but I cannot do that in Vim.

You need to look at `SendEnv` in [ssh_config](https://linux.die.net/man/5/ssh_config), and `AcceptEnv` in [sshd_config](https://linux.die.net/man/5/sshd_config). You need to make sure `TERM_PROGRAM`, `TERM_PROGRAM_VERSION`, `VTE_VERSION` (if you're using a VTE-based terminal), `XTERM_VERSION` (if you're using xterm), and possibly `KONSOLE_DBUS_SESSION` (if you're using an older KDE terminal) are forwarded and accepted by the other end.

Alternatively, you can set `g:togglecursor_force` to the right style for your terminal in your vimrc file, as [mentioned in the documentation](https://github.com/jszakmeister/vim-togglecursor/blob/master/doc/togglecursor.txt#L64).  An example for XTerm-style terminals is:

    let g:togglecursor_force = 'xterm'

Make sure to include this before the plugin is loaded.

**Comment by PezCoder** [comment]
That worked like a charm @jszakmeister ! Thanks for your time.
