### ISSUE TITLE
Wrong cursor in 'r' mode

### ISSUE THREAD

**Issue by hutou** [jszakmeister/vim-togglecursor#35]
Hi,
When quitting Insert Mode with ESC and hitting 'r' to replace one character, the cursor is rendered as a vertical line, not an underline.
Thanks for this plugin.

**Comment by jszakmeister** [comment]
Try the current master branch and see if that does the trick for you.  It used to be that there was no way to fix this in the terminal, but 7.4.687 grew the ability to do so.  So hopefully this fixes the issue for you.
