### ISSUE TITLE
neovim 0.2+ support

### ISSUE THREAD

**Issue by chhschou** [jszakmeister/vim-togglecursor#36]
As of neovim 0.2+ `$NVIM_TUI_ENABLE_CURSOR_SHAPE` is removed: https://github.com/neovim/neovim/wiki/Following-HEAD#20170402

A new way to control cursor shape through guicursor is recommended: https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-shape-in-the-terminal

**Comment by jszakmeister** [comment]
True, but `guicursor` is also enabled by default if Neovim can support it.  Is there something more that you think my plugin should be doing?  It could (maybe) help formulate the `guicursor` line for you based on the settings.  I'm just not sure where to take it.  My main concern in the plugin was Vim support. :-)

**Comment by chhschou** [comment]
Ok I understand now. I was in the process of adding support for vim on hyperterm and nvim doesn't work properly on hyperterm so I thought this maybe the issue (I am on 0.2.0 stable). 

Are you interested in supporting vim for hyperterm (hyper.is)?
Also if you know how to check terminfo for capability to change cursor shape and/or blinking?

**Comment by jszakmeister** [comment]
> Ok I understand now. I was in the process of adding support for vim on hyperterm and nvim doesn't work properly on hyperterm so I thought this maybe the issue (I am on 0.2.0 stable).

I can see why, but Neovim has it's own detection mechanism.  Fixing it would mean fixing it in Neovim directly.

> Are you interested in supporting vim for hyperterm (hyper.is)? Happy to submit a PR.
> Also if you know how to check terminfo for capability to change cursor shape and/or blinking?

I'm certainly not opposed.  I don't really use Hyperterm, but I downloaded it real quick and it looks like the following diff would do the trick:

```diff
diff --git i/plugin/togglecursor.vim w/plugin/togglecursor.vim
index 4397a2c..6ec1f0f 100644
--- i/plugin/togglecursor.vim
+++ w/plugin/togglecursor.vim
@@ -77,6 +77,8 @@ if s:supported_terminal == ""
         let s:supported_terminal = 'xterm'
     elseif $TERM_PROGRAM == "Apple_Terminal" && str2nr($TERM_PROGRAM_VERSION) >= 388
         let s:supported_terminal = 'xterm'
+    elseif $TERM_PROGRAM == "Hyper"
+        let s:supported_terminal = 'xterm'
     elseif $TERM == "rxvt-unicode" || $TERM == "rxvt-unicode-256color"
         let s:supported_terminal = 'xterm'
     elseif str2nr($VTE_VERSION) >= 3900
```

As for querying via terminfo, that has spotty support at best.  The last time I tried such things, I discovered that most terminals did not support interrogating the shape and blinking support.  Also, Vim had no good way of doing this either (without changing Vim itself).  Instead, we have to rely on environmental things to tell us what term program is being used and decide from there.  It stinks.  I wish the query support was there, but it just isn't.

**Comment by chhschou** [comment]
Yeah you diff is pretty much what I have. I have a version check on $TERM_PROGRAM_VERSION because some code I had earlier didn't work. I only targeted version 1.4.2 or later which I've tested.

My own research on the detecting terminfo capability is similar to what you said. Another terminal I'm interested to have cursor shape working is Alacritty. The maintainers are not interested in providing env variable to identify their terminal, but point to terminfo for working things out instead. It looks like it supported cursor shape but not blinking, so I will be trying to find out via terminfo if that was clearly reported.

**Comment by jszakmeister** [comment]
> I have a version check on $TERM_PROGRAM_VERSION because some code I had earlier didn't work.

Was that because the terminal didn't support it, or do you think there was another issue involved?

> The maintainers are not interested in providing env variable to identify their terminal, but point to terminfo for working things out instead.

I've run into that as well, and it's a frustrating place to be.  So many don't support the necessary bits that it's hard to convince them it's necessary, and the ones that do you can't leverage because Vim doesn't expose what you need. :-(

> It looks like it supported cursor shape but not blinking, so I will be trying to find out via terminfo if that was clearly reported.

It looked to me like blinking was supported.  If you do:

    printf '\x1b[0 q'

on the command line, you should see a blinking block cursor.  It worked for the version of Hyperterm I downloaded this morning (I'd tell you the version, but I've deleted it already).  Trying to get that via terminfo via Vim is an uphill battle.  I don't know of any way to query specific capabilities in Vim via terminfo. :-(

**Comment by chhschou** [comment]
> Was that because the terminal didn't support it, or do you think there was another issue involved?

It might've been other issues. I had some code from vim wikia like this in my .vimrc:
```vim
if &term =~ '^xterm\\|rxvt'
  " blinking vertical bar
  let &t_SI .= "\<Esc>[5 q"
  " solid block
  let &t_EI .= "\<Esc>[2 q"
  " 1 or 0 -> blinking block
  " 3 -> blinking underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
endif
```
> It looked to me like blinking was supported. If you do: `printf '\x1b[0 q'`

Thanks, I didn't realize you can test via command line like this. Hyper term is all good now, the terminal I'm having an issue with is Alacrity. The code you had above does not produce a blinking cursor in that ferminal, I guess that says it really doesn't support blinking.
