### ISSUE TITLE
Cursor shape Vim+Tmux

### ISSUE THREAD

**Issue by hutou** [jszakmeister/vim-togglecursor#38]
Hi,
I'm using your plugin with Vim (Version 8.0)  in Gnome TrueColor terminal and it works fine. 
Under Tmux (version 2.6 since today!) however, the behaviour is not correct: 

- On opening a file in Vim, the cursor is a static vertical beam
- On entering Insert Mode : the vertical beam blinks once, then become static again
- On returning to Normal mode : a block shape blinks once, then vertical static beam again
- On entering Replace Mode (R) : underline cursor blinks once, then vertical static beam
So, it seems the correct shape cannot remain active.
Do you know of a possible solution for this ?
Thanks

**Comment by jszakmeister** [comment]
Which Vim?  Which OS are you running?  I'm running on macOS and launch tmux 2.6 and can run Vim with the cursor behaving as expected.  So at the moment, it sounds like there might be some new "feature" of gnome-terminal, or maybe the two are interacting badly?  What are TERM and COLORTERM set to inside of tmux?

**Comment by hutou** [comment]
My system is running ArchLinux 64bits / Gnome (3.24.2) and I am using  vim 8.0 and  tmux 2.6
Here are the variables contents under tmux:
```
$ echo $TERM                                                                                                                                                                                  
xterm-256color                                                                                                                                                                                                                    
$ echo $COLORTERM                                                                                                                                                                             
truecolor 
```
See attached file for more details on my config.
[config.zip](https://github.com/jszakmeister/vim-togglecursor/files/1366424/config.zip)

**Comment by jszakmeister** [comment]
I'd suggest trying to minimize the config to just what is necessary to reproduce the problem and go from there--unfortunately, I don't really have the cycles to mess with your config (or ArchLinux) to figure it out.  Offhand, I don't really see anything that stands out as the culprit.  You could try sending the escape sequences from the terminal yourself (using printf).  That might help determine whether the issue is a Vim one or a terminal one (I kind of suspect the latter).

**Comment by hutou** [comment]
Ok, I'll try your suggestions.
Thanks anyway.

**Comment by hutou** [comment]
I reopen this issue as I think I have found the origin of the problem, but could only imperfectly solve it.
First, under Gnome-terminal, it is possible to choose the cursor shape (block, vertical beam or underscore). This choice determines the cursor shape for the normal mode in Vim, so it is mandatory to choose the block shape.
Second, if, in the ~/.inputrc file,  the editing mode is set to vi with
`set editing-mode vi  `  
then, it is possible to change the cursor shape to tell the user if he is in normal (block) or insert (beam) mode with the following instructions :
```
set show-mode-in-prompt on
set vi-ins-mode-string \1\e[6 q\2
set vi-cmd-mode-string \1\e[2 q\2 
```  
In fact, these last 2 instructions are the culprit for the odd behaviour under vim/tmux.
Once removed, your plugin perfectly renders cursor shape under vim/bash and vim/tmux.

If instead of modifying the cursor shape, I simply display a string before the prompt telling if mode is Normal or Insert, the problem does not occur.
```
set show-mode-in-prompt on                      
set vi-ins-mode-string "\1\e[1;31m\2(Insert)\1\e[0m\2"                           
set vi-cmd-mode-string "\1\e[1;31m\2(Normal)\1\e[0m\2"
```                       

To me, this workaround is less satisfactory, however.
So, given these informations, can you see a possible solution to get a seamless
behaviour everywhere ?

Thanks

**Comment by jszakmeister** [comment]
Good job for keeping at it @hutou!

So, off-hand I'm not entirely sure, but here's something to try:

1. Add this to your vimrc: `let g:togglecursor_disable_tmux = 1`
2. Add this to your tmux.conf: `set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'`
3. Fire up tmux and Vim and see how it interacts.

Step 1 disables the automatic wrapping I do to get the cursor shape to slide through tmux's interception of escape sequences for the terminal.  Step 2 teaches tmux to recognize the DECSCUSR escape sequences and, hopefully, behave appropriately.

Let me know how it goes!

**Comment by hutou** [comment]
Unfortunately, it doesn't work : under vim/tmux, the cursor's shape doesn't show mode change : it keeps displaying a block shape.
Thanks anyway!

**Comment by jszakmeister** [comment]
Bummer. :-(  If I think of anything else, I'll let you know.  I'm fairly sure there's a way, it's just the (complicated) matter of knowing what knobs to turn.
